[package]
name = "acceleration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "acceleration"
path = "src/cli.rs"

[dependencies]
sha-1 = "0.10.0"
rsa = "0.5.0"
memmap = "0.7"
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
bitflags = "1.3"
chrono = "0.4"
byteorder = "1.4"
num_enum = "0.5"