[package]
name = "stfs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sha-1 = "0.10.0"
#rsa = "0.5.0"
thiserror = "1.0"
bitflags = "1.3"
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
byteorder = "1.4"
num_enum = { version = "0.5" }
serde = { version = "1.0", features = ["derive", "rc"] }
parking_lot = { version = "0.12", features = ["serde"] }