pub const HASHES_PER_HASH_TABLE: usize = 0xAA;
pub const HASHES_PER_HASH_TABLE_LEVEL: [usize; 3] = [
	HASHES_PER_HASH_TABLE,
	HASHES_PER_HASH_TABLE * HASHES_PER_HASH_TABLE,
	HASHES_PER_HASH_TABLE * HASHES_PER_HASH_TABLE * HASHES_PER_HASH_TABLE,
];
pub const DATA_BLOCKS_PER_HASH_TREE_LEVEL: [usize; 3] =
	[1, HASHES_PER_HASH_TABLE, HASHES_PER_HASH_TABLE * HASHES_PER_HASH_TABLE];
pub const BLOCK_SIZE: usize = 0x1000;
pub const MAX_IMAGE_SIZE: usize = 0x4000;
