[package]
name = "acceleration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7"
structopt = "0.3"
anyhow = "1.0"
serde = { version = "1.0" }
stfs = {version = "0.1", path = "../stfs"}